// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407074956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mains"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Appetizers"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Classic Molokhia served with white rice.",
                            FamilyId = 1,
                            Name = "Molokhia with Rice",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Description = "Warak enab stuffed with rice and herbs.",
                            FamilyId = 1,
                            Name = "Stuffed Vine Leaves",
                            Price = 70m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Lentils, pasta, rice with spicy sauce.",
                            FamilyId = 1,
                            Name = "Koshari Plate",
                            Price = 60m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Warm Egyptian lentil soup.",
                            FamilyId = 1,
                            Name = "Lentil Soup",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Marinated grilled chicken with rice.",
                            FamilyId = 1,
                            Name = "Grilled Chicken with Rice",
                            Price = 95m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Fresh sea bass grilled with herbs.",
                            FamilyId = 2,
                            Name = "Grilled Sea Bass",
                            Price = 150m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Crispy fried calamari rings.",
                            FamilyId = 2,
                            Name = "Fried Calamari",
                            Price = 110m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Shrimp cooked in clay pot with veggies.",
                            FamilyId = 2,
                            Name = "Shrimp Tagine",
                            Price = 140m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Rich seafood soup.",
                            FamilyId = 2,
                            Name = "Fish Soup",
                            Price = 65m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Fresh lemon mint drink.",
                            FamilyId = 2,
                            Name = "Lemon Mint Juice",
                            Price = 30m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Traditional semolina cake with syrup.",
                            FamilyId = 3,
                            Name = "Basbousa",
                            Price = 45m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Crispy kunafa filled with cream.",
                            FamilyId = 3,
                            Name = "Kunafa with Cream",
                            Price = 55m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Creamy rice pudding with nuts.",
                            FamilyId = 3,
                            Name = "Rice Pudding",
                            Price = 35m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Layers of filo with nuts and syrup.",
                            FamilyId = 3,
                            Name = "Baklava",
                            Price = 60m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Strong Turkish-style coffee.",
                            FamilyId = 3,
                            Name = "Turkish Coffee",
                            Price = 25m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Kebab, kofta, and shish tawook.",
                            FamilyId = 4,
                            Name = "Mixed Grill Platter",
                            Price = 180m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Grilled kofta served with tahini sauce.",
                            FamilyId = 4,
                            Name = "Kofta with Tahini",
                            Price = 120m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Spicy grilled chicken wings.",
                            FamilyId = 4,
                            Name = "Chicken Wings",
                            Price = 90m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Fresh salad with toasted bread.",
                            FamilyId = 4,
                            Name = "Fattoush Salad",
                            Price = 50m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Cold karkade drink.",
                            FamilyId = 4,
                            Name = "Fresh Hibiscus Drink",
                            Price = 30m
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Traditional Egyptian home-cooked meals.",
                            Location = "Cairo",
                            Name = "Ahmed Family Kitchen",
                            UserId = 1,
                            WhatsAppNumber = "+201000000001"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Seafood specials from our family to yours.",
                            Location = "Alexandria",
                            Name = "Hassan Home Bites",
                            UserId = 2,
                            WhatsAppNumber = "+201000000002"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Homemade desserts and baked goods.",
                            Location = "Giza",
                            Name = "Fatima's Sweet Corner",
                            UserId = 3,
                            WhatsAppNumber = "+201000000003"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Grilled meats and hearty mains.",
                            Location = "Mansoura",
                            Name = "Samir's Grill House",
                            UserId = 4,
                            WhatsAppNumber = "+201000000004"
                        });
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1",
                            Name = "Family",
                            NormalizedName = "FAMILY"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "3",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-STAMP-1",
                            Email = "family1@homebites.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FAMILY1@HOMEBITES.TEST",
                            NormalizedUserName = "FAMILY1@HOMEBITES.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEPwvwfU5ZE23+bFoi0kK8vBrvyXTnCgpgoCFvrl3dL6LNL8YQWuaTAFk28CSaUEqdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEC-STAMP-1",
                            TwoFactorEnabled = false,
                            UserName = "family1@homebites.test",
                            UserType = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-STAMP-2",
                            Email = "family2@homebites.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FAMILY2@HOMEBITES.TEST",
                            NormalizedUserName = "FAMILY2@HOMEBITES.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEPwvwfU5ZE23+bFoi0kK8vBrvyXTnCgpgoCFvrl3dL6LNL8YQWuaTAFk28CSaUEqdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEC-STAMP-2",
                            TwoFactorEnabled = false,
                            UserName = "family2@homebites.test",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-STAMP-3",
                            Email = "family3@homebites.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FAMILY3@HOMEBITES.TEST",
                            NormalizedUserName = "FAMILY3@HOMEBITES.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEPwvwfU5ZE23+bFoi0kK8vBrvyXTnCgpgoCFvrl3dL6LNL8YQWuaTAFk28CSaUEqdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEC-STAMP-3",
                            TwoFactorEnabled = false,
                            UserName = "family3@homebites.test",
                            UserType = 1
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC-STAMP-4",
                            Email = "family4@homebites.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FAMILY4@HOMEBITES.TEST",
                            NormalizedUserName = "FAMILY4@HOMEBITES.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEHIsl1bRy51jouxwrUOXCspQJvpodAgNdJjasSgkv3Uklh48s/F8X5eTMNiV7mFmwg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEC-STAMP-4",
                            TwoFactorEnabled = false,
                            UserName = "family4@homebites.test",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Dish", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Family", "Family")
                        .WithMany("Dishes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("DataAccess.Entities.Family", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", "User")
                        .WithOne("Family")
                        .HasForeignKey("DataAccess.Entities.Family", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DataAccess.Entities.Family", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Family");
                });
#pragma warning restore 612, 618
        }
    }
}
