// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Dishes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sweets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bakery"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Slow-cooked whole chicken on a bed of spiced rice with nuts and raisins.",
                            FamilyId = 1,
                            ImageUrl = "/images/dishes/oozi.jpg",
                            Name = "Chicken Oozi",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Crispy bulgur shells stuffed with seasoned ground beef, onions, and pine nuts.",
                            FamilyId = 1,
                            ImageUrl = "/images/dishes/kibbeh.jpg",
                            Name = "Fried Kibbeh",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Soft semolina cake soaked in rose-water syrup, topped with almonds.",
                            FamilyId = 1,
                            ImageUrl = "/images/dishes/basbousa.jpg",
                            Name = "Basbousa",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Tender slow-roasted lamb over fragrant basmati rice cooked in a tandoor oven.",
                            FamilyId = 2,
                            ImageUrl = "/images/dishes/mandi.jpg",
                            Name = "Lamb Mandi",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Traditional diamond-shaped Iraqi bread, fresh out of the oven — fluffy inside, crispy outside.",
                            FamilyId = 2,
                            ImageUrl = "/images/dishes/samoon.jpg",
                            Name = "Samoon Bread",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Grape leaves and vegetables stuffed with spiced rice and minced meat, cooked in tomato broth.",
                            FamilyId = 2,
                            ImageUrl = "/images/dishes/dolma.jpg",
                            Name = "Baghdadi Dolma",
                            Price = 300.00m
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Authentic Syrian home-cooked meals prepared with love in Istanbul.",
                            Location = "Fatih, Istanbul",
                            Name = "Sham Kitchen",
                            ProfileImageUrl = "/images/profiles/sham_kitchen.jpg",
                            UserId = 1,
                            WhatsAppNumber = "+905311111111"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "The best Mansaf, Mandi, and traditional Iraqi dishes in the city.",
                            Location = "Esenyurt, Istanbul",
                            Name = "Iraqi Flavors",
                            ProfileImageUrl = "/images/profiles/iraqi_flavors.jpg",
                            UserId = 2,
                            WhatsAppNumber = "+905322222222"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sham@homebites.com",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "iraqi@homebites.com",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Dish", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Family", "Family")
                        .WithMany("Dishes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("DataAccess.Entities.Family", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "User")
                        .WithOne("Family")
                        .HasForeignKey("DataAccess.Entities.Family", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DataAccess.Entities.Family", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Family");
                });
#pragma warning restore 612, 618
        }
    }
}
